name: Cargo Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v3
    - name: rustup
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  check_formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rustup update
      run: rustup update stable && rustup default stable
    - name: check formatting
      run: cargo fmt --check
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rustup update
      run: rustup update stable && rustup default stable
    - name: install clippy
      run: rustup component add clippy
    - name: check formatting
      run: cargo clippy

